### ISSUE TITLE
Sometimes does not detect JW Library Media Window

### ISSUE THREAD

**Issue by Jeremy909** [AntonyCorbett/JwlMediaWin#11]
When JW Library was launched at our mid week meeting yesterday, JwMediaWin was running but did not detect the media window or give the notification 'JW Library Media Window fixed'. It has done this only once before. Most meetings has worked first time, but when this happens I cannot find a way to fix it or find a way to restart JwMediaWin other than to log out of Windows and log back in. It then worked fine after that.

**Comment by scottys94** [comment]
If you want to re-launch JwlMediaWin without logging off and then back in, you can run the executable for it which is located in the Program Files folder. If your computer is running 64-bit Windows, the path is: C:\Program Files (x86)\JwlMediaWin. If you’re running 32-bit Windows, the path is: C:\Program Files\JwlMediaWin. There you’ll see a JwlMediaWin.exe file. You can right-click that EXE file and select Send To > Desktop, and it will create a shortcut on your desktop for it. Simply double-click the shortcut to relaunch JwlMediaWin. But why it’s not detecting the media display in the first place is still an issue.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Jeremy909** [comment]
Creating a shortcut to JwlMediaWin.exe will definitely be helpful,. thanks.

If it may be relevant, this has happens when the computer is stated from Shut Down. It is not usually left in Sleep or Hibernate.

**Comment by KenFrantz** [comment]
If more than one congregation uses the Hall, like we do here in Arizona, we never shutdown, sleep, or hibernate the PC. Each congregation has a separate account. When done, the operator signs out and locks the computer. That way it is free to download and install any updates that come along. We have never had any issues with this procedure.

**Comment by Tdanforth** [comment]
My hall was having the same issue. It would either show the Only T meeting countdown and the JWL media window would not return or vice versa. I discovered I was having the same thing happen on my computer at home. I discovered that uninstalling JwlMediaWin then reinstalling it fixed the problem. It appears it was not running correctly. 

I went to the hall today to do the same thing on the computer and it fixed it as well. After I did that, I did extensive testing (from shutdown and sleep) to make sure the meeting countdown showed and returned to the JWL media window when it has finished.

Before uninstalling, right-click the JwlMediaWin icon (usually in the system tray on the taskbar)
![image](https://user-images.githubusercontent.com/51468761/59557239-cee37d80-8fa2-11e9-8f88-418c4bd9d18b.png)
and click "Stop JWL Media Fix"

To uninstall for 64-bit, go to File Explorer and navigate to (or enter the address),  C:\Program Files (x86)\JwlMediaWin or for 32-bit, C:\Program Files\JwlMediaWin.

Double-click the unins000 to run the uninstall application. 
![image](https://user-images.githubusercontent.com/51468761/59557291-35b56680-8fa4-11e9-80c9-3899a7f04752.png)

Download and run the JwlMediaWinSetup.exe file from the Wiki page to reinstall.

When you open JWL, it should now display the notification "Found JW Library media window and fixed it". At times, my computer at home will not show the notification. Another way you can tell it's working is it will flash the year text background on JWL for 2 seconds (which usually always happens).

The big test will be tomorrow (Sunday) to see if it will work without me intervening or doing the tests. I'm pretty confident that it'll work. I'll report back to tell what happens.

**Comment by KenFrantz** [comment]
We have four congregations using the PC. We never put our PC to sleep and we never shut it down. You are forcing it to update when you least want it to. We do a restart after every meeting and go to the lock screen so the next congregation has a fresh start. We have the update set to run automatically between 11PM and 7AM. Also, we just don't have the same issues as others are reporting with transitions between OnlyM and JWL. We only use the tools for their intended purpose. If we know we will need OnlyM, we start it first and then start JWL. We've never had an issue with not getting back to the correct screen.

Ken
C: (518) 947-4709

________________________________

**Comment by KenFrantz** [comment]
Oh. One thing I forgot to mention, each congregation has its own separate account on the PC. So they can choose the correct congregation from the lock screen.

Ken
C: (518) 947-4709

________________________________

**Comment by CovenantJunior** [comment]
I'm facing similar issues with Windows 11.
