### ISSUE TITLE
JW Library Media Window Issues

### ISSUE THREAD

**Issue by scottys94** [AntonyCorbett/JwlMediaWin#12]
We recently encountered some issues with the JW Library media window, and I was wondering if anyone else also experienced them. We are using JwlMediaWin, but I have yet to figure out if that’s a contributing factor.

If someone clicks the media window for JW Library on the taskbar while it is already active on the TV screens, Windows will minimize it. However, the issue comes when someone clicks the media window again to restore it. When this happens, the year text will appear on the TV’s for approximately 7 seconds, and then disappear for about 1 second. This cycle will repeat itself continuously until someone closes JW Library completely and then opens it again.

While the issue was happening, I decided to play a video and noticed that the video was not filling the entire screen - as though the resolution was changed. But after closing and re-opening JW Library, the video will fill the entire screen.

After finding out about this, I notified the Sound operators to not click on the JW Library media window while it is already active on the TV screens. I’m still trying to figure out why doing so will create these issues.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Spenser715** [comment]
perhaps a simple workaround would be to turn on taskbar on second screen and set so JW library media screen is only visible there. then no one can press the thumbnail for it. In case you don't know where those setting are, Go to Windows settings Search Taskbar Settings>scroll down to the section Multiple Displays> make sure taskbar on all displays is on and set Show taskbar buttons on... to Taskbar where window is open.

**Comment by scottys94** [comment]
>perhaps a simple workaround would be to turn on taskbar on second screen and set so JW library media screen is only visible there. then no one can press the thumbnail for it. In case you don't know where those setting are, Go to Windows settings Search Taskbar Settings>scroll down to the section Multiple Displays> make sure taskbar on all displays is on and set Show taskbar buttons on... to Taskbar where window is open.

@Spenser715 Thank you.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
