### ISSUE TITLE
Second screen fails to return to last image

### ISSUE THREAD

**Issue by KenFrantz** [AntonyCorbett/JwlMediaWin#14]
I ran into an interesting issue while preparing to conduct tonight's CBS on the neighborly Samaritan. This is at home after I installed the latest media win app.

In JW Library, I navigated from the workbook to jy Chap. 73 via the link. I clicked the title bar in the right-hand pane to navigate to the book. So I had all my notes available to me. I clicked the main picture at the top to display it on the second screen. I opened Luke 10:25-37 in the right-hand pane via the link at the top of the chapter and then opened the Study Bible from the title bar at the top of the right-hand pane. Now I have the scripture open and access to all the study notes.

On Luke 10:30, the study notes include a video that I wanted to display. So I clicked the go button on the video link and the video played through on the second screen. However, when the video was finished, I was expecting the image of the Samaritan to return. Instead, the second screen returned to the year text. Oops. I had to leave the Bible and go back to the book so I could click the picture to redisplay it on the second screen, then return to the Bible to continue preparing the part.

It was tedious to redisplay the original image in that way. I don't know if it's possible to keep a stack of what has been displayed to allow backtracking, or if this situation is just a one-off.

Thanks for listening,
Ken

**Comment by AntonyCorbett** [comment]
@KenFrantz Hi Ken. This is just the way JW Library works and the behaviour is unaffected by JwlMediaWin. Regards, Antony

**Comment by KenFrantz** [comment]
Yeah, I thought as much. Just thought I'd mention it.

Ken
C: (518) 947-4709

________________________________
