### ISSUE TITLE
Not Displaying JW Library with SbJwlLauncher

### ISSUE THREAD

**Issue by AnthonyG83** [AntonyCorbett/JwlMediaWin#16]
I created a .bat file to open SbJwlLauncher, Only M, Only T, and the program for streaming our meetings. JW Library won’t display the yeartext on open. The pre-meeting timer will come on and display, but it won’t display the yeartext after that. If I close JW Library and open it by itself without SbJwlLauncher it functions as expected. I am using the latest version of JwlMediaWin.

**Comment by AntonyCorbett** [comment]
Does it work ok when SbJwlLauncher is run manually rather that from a batch file?

**Comment by AntonyCorbett** [comment]
Also, what version of SbJwlLauncher are you using please?

**Comment by AnthonyG83** [comment]
It seems to work okay when it is run manually. It is version 1.0.0.4 of SbJwlLauncher.

**Comment by AntonyCorbett** [comment]
@AnthonyG83 Please upgrade to the latest version and try the batch file again

**Comment by AnthonyG83** [comment]
It looks as if the latest version is 1.0.0.4. Is there a newer version?

**Comment by AntonyCorbett** [comment]
You're right. Can you show the text of the batch file please?

**Comment by AntonyCorbett** [comment]
No response so closing for now
