### ISSUE TITLE
Delay with Detecting JWL Media Window

### ISSUE THREAD

**Issue by scottys94** [AntonyCorbett/JwlMediaWin#17]
[log-20201031.txt](https://github.com/AntonyCorbett/JwlMediaWin/files/5505817/log-20201031.txt)
Recently I have noticed that on random occasions, when launching JW Library with a separate media window, JwlMediaWin will take 60 seconds before recognizing the media window on my second monitor. I tried closing and re-opening JW Library numerous times, stopping JwlMediaWin and running it again, rebooting Windows, etc. I even re-installed JwlMediaWin. As I mentioned, it happens randomly. So to estimate, out of 10 times that I open JW Library, this issue will occur 8 times. The other 2 times it will detect the media window after about 5 seconds. What can cause this to occur? I attached the application log for your reference. I'm running JwlMediaWin version 1.0.0.9 on Windows 10 20H2

**Comment by AntonyCorbett** [comment]
@scottys94 Is it on a single monitor system (using the new JWL feature that allows you to display media in a window) or dual?

**Comment by scottys94** [comment]
>@scottys94 Is it on a single monitor system (using the new JWL feature that allows you to display media in a window) or dual?

@AntonyCorbett This is using dual monitors

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ColinAAvey** [comment]
I have also experienced this problem for several months. With me it seems related to how long I have been logged in. If I open JWLib fairly quickly after logging in, having waited to see JwlMediaWin load, then it can be sometime before it applies the fix. However, if I check my email first (~10 mins) then the fix will normally apply in a few seconds. I have also got into the habit of waiting for the fix to apply before opening another app.

I have been blaming my setup, as this is on my main dev box and has a lot going on in the background. I haven't spent a huge amount of time investigating, but more than happy to put some time in if it will help.

Thanks for you hard work Antony.
Colin

Dual monitors, Quadro K5000. I have seen isse on various versions/updates of Win 10 Pro x64.

OS Name	Microsoft Windows 10 Pro
Version	10.0.19042 Build 19042
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Manufacturer	FUJITSU
System Model	CELSIUS R920
System Type	x64-based PC
System SKU	S26361-Kxxx-Vyyy
Processor	Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, 2501 Mhz, 6 Core(s), 12 Logical Processor(s)
Processor	Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, 2494 Mhz, 6 Core(s), 12 Logical Processor(s)
BIOS Version/Date	FUJITSU // American Megatrends Inc. V4.6.5.1 R1.13.0 for D3118-A1x, 20/09/2013
SMBIOS Version	2.7
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	FUJITSU
BaseBoard Product	D3118-A1
BaseBoard Version	S26361-D3118-A1
Platform Role	Workstation
Secure Boot State	Unsupported
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Locale	United Kingdom
Hardware Abstraction Layer	Version = "10.0.19041.488"
Time Zone	GMT Standard Time
Installed Physical Memory (RAM)	32.0 GB
Total Physical Memory	31.9 GB
Available Physical Memory	23.4 GB
Total Virtual Memory	36.7 GB
Available Virtual Memory	27.2 GB
Page File Space	4.75 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	Off
Virtualisation-based security	Running
Virtualisation-based security required security properties	
Virtualisation-based security available security properties	Base Virtualisation Support, DMA Protection
Virtualisation-based security services configured	
Virtualisation-based security services running	
Device Encryption Support	Elevation Required to View
A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by AntonyCorbett** [comment]
@scottys94 Any comments on the observations by @ColinAAvey please? I've had a brief review of the code and can't explain what you are experiencing, unless the service is being loaded as low priority on a very busy machine during start up.

**Comment by scottys94** [comment]
>@scottys94 Any comments on the observations by @ColinAAvey please? I've had a brief review of the code and can't explain what you are experiencing, unless the service is being loaded as low priority on a very busy machine during start up.

@AntonyCorbett Thank you both for the feedback. I haven’t noticed a specific pattern for this issue. Sometimes it happens when I open JW Library just after logging in. Other times, my computer would be on for a while and I would still notice it. I wouldn’t open other apps while waiting for JwlMediaWin to detect the media display. If I find any specific cause I will reply back, otherwise this can be closed out for now.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
