### ISSUE TITLE
Apparent Virus MS AV

### ISSUE THREAD

**Issue by simonsjv** [AntonyCorbett/JwlMediaWin#19]
![image](https://user-images.githubusercontent.com/77863600/105560188-42489600-5d67-11eb-9a53-9cb2c269690e.png)
Just concerned for this one. Do you believe it is a False Positive?

Regards Simon

**Comment by AntonyCorbett** [comment]
@simonsjv It's a false positive. Use VirusTotal for a more balanced picture
