### ISSUE TITLE
Trojan:MSIL/Masslogger.VN!MTB

### ISSUE THREAD

**Issue by davidrobertsen** [AntonyCorbett/JwlMediaWin#20]
![image](https://user-images.githubusercontent.com/67205138/122523500-5f804880-d017-11eb-8e20-526a2564ede6.png)

I'm not able to download as Windows Defender finds a virus: https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aMSIL%2fMasslogger.VN!MTB&threatid=2147758432

**Comment by AntonyCorbett** [comment]
@davidrobertsen Thanks. Temporarily turn off Defender Real-time protection to allow you to download and install. BTW, there is no key-logging or other malware in the application.
