### ISSUE TITLE
Microsoft Defender

### ISSUE THREAD

**Issue by mobiletrainer1** [AntonyCorbett/JwlMediaWin#21]
When I attempt to download JwlMediaWinSetup Microsoft Defender intercepts it stating it contains a Trojan:MSIL/Masslogger.VN!MTB.

I know I could bypass it don't know if it's a false positive or not.

Terry

![JWL media Win setup error message](https://user-images.githubusercontent.com/86566150/123552028-4f1c4c00-d742-11eb-8ce3-fdcf8ecef1e5.JPG)

**Comment by AntonyCorbett** [comment]
@mobiletrainer1 please see #19 and #20

**Comment by mobiletrainer1** [comment]
Sorry about that. I'm new to github. I didn't know to look at the closed comments. Keep up the good work, brother.

**Comment by AntonyCorbett** [comment]
@mobiletrainer1 no problem. Thanks for the report
