### ISSUE TITLE
Occasional Audio Issues with new JW Library update

### ISSUE THREAD

**Issue by scottys94** [AntonyCorbett/JwlMediaWin#22]
My congregation began to experience some audio issues with JW Library and Zoom as of last week. This was after an update was released to JW Library (ver. 12.4.150). My Zoom host device consists of dual monitors, JW Library media window on second display, Zoom version 5.7.1, and JwlMediaWin 1.0.0.9.

From Zoom, I share my entire second screen for the videos. At least once during the meeting, I would start a video and get no audio. This would happen randomly. Sometimes it would work fine for the first 1 or 2 videos, then the 3rd would give us no audio. Other times it would start with the first video. Our workaround was to stop the video then play it again. Then it would work normally. We were struggling to figure out if the issue was coming from JW Library or Zoom.

After our meeting, I decided to do some testing. I was able to reproduce this issue fairly quickly. I started a video and was getting no audio. While the video was still playing, I went into the JW Library settings on my host device and disabled the option "Play video on second display." Then I re-enabled it, and immediately the audio started coming through! At that point, I was convinced the issue was something related to JW Library. We only started experiencing this after updating to JW Library version 12.4.150 which was released last week. I just wanted to post this in case anyone else begins experiencing the same issues. If anyone has any suggestions or ideas, please let me know.

**Comment by AntonyCorbett** [comment]
@scottys94 Is the second monitor also an audio device?

**Comment by scottys94** [comment]
@AntonyCorbett No, my monitors are not audio devices.

**Comment by scottys94** [comment]
To further troubleshoot this issue, I decided to downgrade the Zoom client on my host device from version 5.7.1 to 5.6.5. Sure enough, I was not able to reproduce the issue on this older version of Zoom. The audio worked consistently each time. But now, the mystery is why the newer Zoom version occasionally doesn't pass audio from JW Library. From every other application, including OnlyM, the audio always worked consistently. Something with Zoom version 5.7.1 and JW Library isn't working well together. I'm not sure if JwlMediaWin is still a likely suspect, since disabling/re-enabling the JWL 2nd display during the issue would restore audio. Regardless, it seems our workaround is to remain on Zoom version 5.6.5 and still use the latest update of JW Library. Hopefully these findings will help others who may be experiencing the same thing.

**Comment by AntonyCorbett** [comment]
@scottys94 Is this issue ongoing?

**Comment by scottys94** [comment]
@AntonyCorbett Thankfully this issue is resolved now. It was only occurring with specific versions of Zoom. With the current version, it works fine.
