### ISSUE TITLE
Zoom Hybrid Meetings

### ISSUE THREAD

**Issue by Jeremy909** [AntonyCorbett/JwlMediaWin#24]
When testing for Hybrid Meetings, I found that JwMediaWin will not allow the Zoom Speaker View Window to be on top of the Yeartext and is hidden behind it. I had to disable it and use JW Library compatibility mode in OnlyM instead.

**Comment by scottys94** [comment]
@Jeremy909 What if you right-click the JwlMediaWin icon in the System Tray and disable "Keep on top"?

**Comment by Jeremy909** [comment]
@scottys94 I did not know that was an option. I just tried it with "Keep on top" disabled and it works. Thanks for the tip.
