### ISSUE TITLE
Prevent minimize when show desktop

### ISSUE THREAD

**Issue by LvDaniel** [AntonyCorbett/JwlMediaWin#4]
Hi Anthony,
Is it possible if accidentally AV operator clicks to show desktop, to prevent JWL media screen to be minimized? Or this is not doable?

And another question (I don't want to raise a separate request as probably can't be implemented)... 
Is it possible JwlMediaWin to have an option to hide the cursor in the media screen?

Thank you.

**Comment by Spenser715** [comment]
In answer to your first question I don't think this is possible but I really don't know.

For your second question you can use a program such as Dual Monitor Tools which allows you to lock the cursor to the main screen so you wont be able to put it on the media screen to be seen.

**Comment by LvDaniel** [comment]
@Spenser715 thanks for feedback, I'm already using Dual Monitor Tools for hiding the cursor. I was just wondering if JwlMediaWin can do this also. If not, won't be a problem, I'll stick to DMT.

**Comment by AntonyCorbett** [comment]
@LvDaniel 

> Is it possible if accidentally AV operator clicks to show desktop, to prevent JWL media screen to be minimized?

No, I don;t think so.

> Is it possible JwlMediaWin to have an option to hide the cursor in the media screen?

I did consider this. It would be possible to lock the mouse to the primary display and release it when OnlyM displays a website, etc. But I think it has the potential to cause too much frustration for novice users.

**Comment by LvDaniel** [comment]
@AntonyCorbett thanks for your comments.
You're probably right, so I'll continue to use DMT.

**Comment by Blann** [comment]
This may be useful – a lightweight utility called ‘7+ Taskbar Tweaker’ which allows, among other things, the ‘Show Desktop’ button to be hidden. 

https://rammichael.com/7-taskbar-tweaker

**Comment by LvDaniel** [comment]
@Blann thanks fot info, I'll have a look.
