### ISSUE TITLE
JWL Media Window on the main screen

### ISSUE THREAD

**Issue by LvDaniel** [AntonyCorbett/JwlMediaWin#5]
Sometimes when JwlMediaWin applies JW Library Fix, JWL media window appears on the main screen, over the JWL main window.
I've experienced this at KH and couple of times at home. Seems like this is happening only when JWL main window is not maximized. It happens randomly and I haven't been able to see a pattern. 
When JWL main window is maximized I haven't seen this happening at all.
The only difference between Home and KH's setup is that I don't use a 3rd screen at home (I don't know if this makes any difference).

I also noticed that when JwlMediaWin applies JW Library Fix, if JWL is not maximized, yeartext flashes once covering JWL main window (on the main screen) and after is displayed on the 2nd screen... but probably this is the normal behavior. 

Below is a screenshot with the mention that I've moved a bit JWL media window just to see the main window which is underneath.

![jwlm 1st screen](https://user-images.githubusercontent.com/45002147/52169723-d6b62a00-2745-11e9-90f9-15d49a3613d1.png)

**Comment by scottys94** [comment]
The same thing has also happened to me a few times.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by oonakannanshioanesh33j3m3** [comment]
i experienced same issue

**Comment by AntonyCorbett** [comment]
I have not been able to reproduce the issue but have guessed at what may be happening and applied a 'fix' based on this assumption!

**Comment by LvDaniel** [comment]
@AntonyCorbett unfortunately I still have this issue even using the latest update.
I have no idea what could be. At home it's pretty hard to reproduce it (almost impossible since 1.0.0.5) but at KH let's say that there are 50% chances to came across this issue.
The only workaround is to have JWL main window maximized. But some congregations from our hall are using JWL window half screen so this workaround can't be applied all the time.
Do you happen to know if there's a way to enforce JWL main window to be maximized at open? 
Thanks for all your help and advices.

**Comment by AntonyCorbett** [comment]
@LvDaniel What does the log show when you experience this bug please?

**Comment by LvDaniel** [comment]
@AntonyCorbett I haven't thought to check the log since the app doesn't crash or something like this. I'll check it tomorrow's evening and I'll let you know.
Another difference I spotted is that at KH I don't get the information message when JwlMediaWin applies the fix (on bottom right). But probably this is from settings.

**Comment by AntonyCorbett** [comment]
> I don't get the information message when JwlMediaWin applies the fix (on bottom right).

@LvDaniel That's very useful to know. I have attempted another fix (latest pre-release), but I doubt it will work! Your log content will be helpful.

**Comment by LvDaniel** [comment]
@AntonyCorbett sure, I'll also install the pre-release tomorrow and let you know how it goes. Thanks for your precious help.

**Comment by LvDaniel** [comment]
@AntonyCorbett I've test this at work also. When using version 1.0.0.3 and 1.0.0.5 I encounter this issue all the time (I didn't expect that). When using 1.0.0.6 everything works fine.
Logs don't give many details but maybe will be helpful for you. Please see them attached.
[1.0.0.3_log-20190214.txt](https://github.com/AntonyCorbett/JwlMediaWin/files/2863882/1.0.0.3_log-20190214.txt)
[1.0.0.6_log-20190214.txt](https://github.com/AntonyCorbett/JwlMediaWin/files/2863883/1.0.0.6_log-20190214.txt)
[1.0.0.5_log-20190214.txt](https://github.com/AntonyCorbett/JwlMediaWin/files/2863884/1.0.0.5_log-20190214.txt)
I'll test tonight 1.0.0.6 version at KH and let you know the results.

I'll give you some details about the setup, maybe will be helpful. 
At work I have 3 monitors, 2 of them connected to the on-board graphic card (Monitor1 & 2) and one connected to a USB to DVI Adapter (Monitor3). JWL main window is displayed on Monitor1, while Monitor2 is the 2nd display (JWL Media Window).
At KH, 2 monitors are connected to the on-board graphic card, one being the main display and 2nd being the Media display. Third monitor is a portable monitor (Asus MB169B+) which is connected via USB to the PC and it's used for timer (OnlyT).

**Comment by AntonyCorbett** [comment]
@LvDaniel Thanks. Look forward to your next report!

**Comment by LvDaniel** [comment]
@AntonyCorbett I've tested the latest release (1.0.0.6) last evening at KH and I haven't encounter this issue anymore. Everything works fine now.
Thanks a lot Antony for all your efforts to solve this.

**Comment by AntonyCorbett** [comment]
@LvDaniel Excellent - thanks.

**Comment by TizianoNoto** [comment]
@AntonyCorbett I tried to take a look at the code but it looks like you forgot to push the latest commits.

**Comment by AntonyCorbett** [comment]
@TizianoNoto you're right, thanks. Now pushed.
