### ISSUE TITLE
Reihenfolge Starten des Programms 

### ISSUE THREAD

**Issue by MisterTob** [AntonyCorbett/JwlMediaWin#6]
Hallo
Ist ausschlaggebend, was Zuerst gestartet wird?
Also erst JwLibrary und dann jwlMediaWin oder erst JwlMediaWin und dann JwLibrary.?

**Comment by LvDaniel** [comment]
@MisterTob JwlMediaWin will automatically start on Windows "startup". You just need to install it and that's it.
For more details please see the wiki.
https://github.com/AntonyCorbett/JwlMediaWin/wiki

**Comment by MisterTob** [comment]
Ok. Irgendwelche Einstellungen müssen aber nicht gemacht werden?
Aktualisiert sich das Programm selbst?

**Comment by LvDaniel** [comment]
Minimal settings can be made as they are presented in the wiki. You need to update it manually.

**Comment by MisterTob** [comment]
Danke für die Hilfe von euch.

Gestern ist JwLibrary während der Zusammenkunft dauernd abgestürzt. 

Muss ich wenn ich JwlMediaWin verwende bei den Programmen OnlyT, OnlyV und OnlyM den Kompatibel Modus ausschalten oder spielt es keine Rolle ob dieser jetzt aktiv ist oder nicht

**Comment by AntonyCorbett** [comment]
It doesn't matter if the JWL compatibility mode is on or off
